#!/usr/bin/env python3
"""
Electronic keyboard frequency calculator.

Computes for each of the 88 keys:
  - Theoretical frequency:  freq[k] = 440 * 2^((k - 48) / 12),  k in [0, 87]
  - Actual frequency:        freq_actual = freq_word * CLK_FREQ / 2^32
  - Frequency deviation:     error_ppm = (freq_actual - freq) / freq * 1e6

Usage:
    python calc_freq.py                         # default CLK_FREQ = 50_000_000
    python calc_freq.py <CLK_FREQ>              # specify clock frequency
"""

import sys
import math

KEY_COUNT = 88

NOTE_NAMES = [
    "A0", "A#0", "B0", "C1", "C#1", "D1", "D#1", "E1", "F1", "F#1", "G1", "G#1",
    "A1", "A#1", "B1", "C2", "C#2", "D2", "D#2", "E2", "F2", "F#2", "G2", "G#2",
    "A2", "A#2", "B2", "C3", "C#3", "D3", "D#3", "E3", "F3", "F#3", "G3", "G#3",
    "A3", "A#3", "B3", "C4", "C#4", "D4", "D#4", "E4", "F4", "F#4", "G4", "G#4",
    "A4", "A#4", "B4", "C5", "C#5", "D5", "D#5", "E5", "F5", "F#5", "G5", "G#5",
    "A5", "A#5", "B5", "C6", "C#6", "D6", "D#6", "E6", "F6", "F#6", "G6", "G#6",
    "A6", "A#6", "B6", "C7", "C#7", "D7", "D#7", "E7", "F7", "F#7", "G7", "G#7",
    "A7", "A#7", "B7", "C8",
]


def theoretical_freq(key_idx: int) -> float:
    """Compute theoretical frequency for key index using 12-TET formula."""
    return 440.0 * (2.0 ** ((key_idx - 48.0) / 12.0))


def freq_word(key_idx: int, clk_freq: int) -> int:
    """Compute the 32-bit phase increment word for a given key and clock."""
    f = theoretical_freq(key_idx)
    return int(round(f * (2.0 ** 32) / float(clk_freq)))


def actual_freq(key_idx: int, clk_freq: int) -> float:
    """Compute the actual frequency produced by the DDS phase accumulator."""
    fw = freq_word(key_idx, clk_freq)
    return fw * clk_freq / (2.0 ** 32)


def error_ppm(key_idx: int, clk_freq: int) -> float:
    """Compute frequency deviation in parts-per-million."""
    f_theory = theoretical_freq(key_idx)
    f_actual = actual_freq(key_idx, clk_freq)
    return (f_actual - f_theory) / f_theory * 1e6


def main():
    if len(sys.argv) >= 2 and sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        return

    clk_freq = int(sys.argv[1]) if len(sys.argv) >= 2 and sys.argv[1].isdigit() else 50_000_000

    print(f"// Frequency Lookup Table Validation (CLK_FREQ = {clk_freq} Hz)")
    print(f"// {KEY_COUNT} keys, k=0(A0) ~ k={KEY_COUNT - 1}(C8)")
    print(f"// Auto-generated by: calc_freq.py\n")

    print(f"// {'Key':>3s} {'Note':>4s} | {'Target(Hz)':>10s} {'Actual(Hz)':>10s} {'PPM':>10s} {'FreqWord':>10s}")
    for k in range(KEY_COUNT):
        f_theory = theoretical_freq(k)
        fw = freq_word(k, clk_freq)
        f_actual = actual_freq(k, clk_freq)
        ppm = error_ppm(k, clk_freq)
        print(f"   {k:3d} {NOTE_NAMES[k]:>4s} | {f_theory:>10.3f} {f_actual:>10.3f} {ppm:>+10.2f} {fw:>10d}")


if __name__ == "__main__":
    main()
